### ISSUE TITLE
Installation fails on Arch Linux with Node v9.10.1

### ISSUE THREAD

**Issue by Nicd** [unicode-org/full-icu-npm#23] opened 2018-04-02 12:54 UTC
```
[codestats@octane assets]$ node -v
v9.10.1
[codestats@octane assets]$ npm -v
5.7.1
[codestats@octane assets]$ npm install full-icu

> full-icu@1.2.1 postinstall /var/codestats/beta/assets/node_modules/full-icu
> node postinstall.js

Note: Your node was compiled to link against an externally-provided ICU, so the locale data is not customizable through this script. Exitting.
npm install icu4c-data@61l (Node 9.10.1 and small-icu 61.1) -> icudt61l.dat
full-icu$ /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@61l
npm ERR! code ETARGET
npm ERR! notarget No matching version found for icu4c-data@61l
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

`full-icu` is a dependency of a dependency so I can't avoid it, and my program has stopped building. It seems version 61l is not pushed to NPM, who handles that? The postinstall script also does not follow the version specified in `package-lock.json`, which would have existed in NPM.

**Comment by srl295** [comment] 2018-04-20 19:36
@Nicd try again. 61l is there.

**Comment by Nicd** [comment] 2018-04-20 19:41
Seems to be working now with a cursory look.

**Comment by srl295** [comment] 2018-04-20 19:52
reopen if not. 

By the way, you filed this 13 hours before I landed 61 in node _master_. https://github.com/nodejs/node/pull/19621#event-1553051856  So you must have explicitly built icu 61?

**Closed** 2018-04-20 19:53 UTC

**Comment by Nicd** [comment] 2018-04-20 19:55
I'm unsure how it ended up like that. I didn't build anything myself, `full-icu` was a dependency of a dependency (Luxon). That version of Node and NPM were installed from Arch Linux official repos.

**Comment by srl295** [comment] 2018-04-20 22:09
Can you send me your arch package versions for Node and npm and icu4c / icu?

**Comment by Nicd** [comment] 2018-04-21 08:02
Do you mean the versions in the original post? Node was 9.10.1, NPM 5.7.1 and full-icu 1.2.1 that resulted in it trying to install `icu4c-data@61l`. Or do you mean something else?

**Comment by srl295** [comment] 2018-04-21 21:56
@Nicd what version of the Arch linux package?  In other words, how did you get ICU 61 13 hours before it was available to Node master, much less any released version? (There are lots of ways, just curious)

**Comment by Nicd** [comment] 2018-04-21 21:59
It's `community/nodejs`, but I have since upgraded it and not sure what the exact package version was, only that it resulted in Node 9.10.1 being installed. Here's the package's history if it helps: https://git.archlinux.org/svntogit/community.git/log/trunk?h=packages/nodejs

**Comment by fzaninotto** [comment] 2018-06-27 09:44
This bug just bit me today, using node 10:

```
$ npm install full-icu

> full-icu@1.2.1 postinstall /Users/francois/tmp/node_modules/full-icu
> node postinstall.js

Note: Your node was compiled to link against an externally-provided ICU, so the locale data is not customizable through this script. Exitting.
npm install icu4c-data@62l (Node 10.5.0 and small-icu 62.1) -> icudt62l.dat
full-icu$ /usr/local/Cellar/node/10.5.0_1/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@62l
```

**Comment by srl295** [comment] 2018-06-27 18:52
@fzaninotto it's not a bug, it means i haven't built the 62l files yet, sorry.
