### ISSUE TITLE
yarn install full-icu is failing

### ISSUE THREAD

**Issue by shouze** [unicode-org/full-icu-npm#9] opened 2016-12-06 20:26 UTC
Related to issue initially reported https://github.com/yarnpkg/yarn/issues/2124#issue-193173249

**Comment by shouze** [comment] 2017-01-09 20:12
ping @srl295 I guess we probably should detect yarn & spawn some yarn add instead of npm install around [here](https://github.com/unicode-org/full-icu-npm/blob/master/install-spawn.js#L21-L28)?

**Comment by srl295** [comment] 2017-02-18 00:41
Makes sense. What's the best way to detect?

**Comment by marvinhagemeister** [comment] 2017-05-15 16:03
We're hit by this exact issue today at work, when we tried to switch some projects over to yarn. Really hope that somebody with more bash experience can chime in. yarn installs are blazing fast compared to npm4

**Comment by srl295** [comment] 2017-05-15 16:09
@marvinhagemeister I have almost no experience with yarn. I tried it once (not with `full-icu` and it worked.)

Just curious, why "bash experience"? This is all JavaScript code.

**Comment by marvinhagemeister** [comment] 2017-05-15 20:00
@srl295 Looking at the code again, I have no idea how I came to the bash conclusion 🐒  Guess it's already to late at work...

Perhaps @kittens or @bestander can help out here?

**Comment by srl295** [comment] 2017-05-15 20:07
https://github.com/unicode-org/full-icu-npm/blob/master/install-spawn.js#L22 

just trying to do `npm install X` where X is calculated.

**Comment by bestander** [comment] 2017-05-15 20:07
Not having enough context on the problem you are solving, it seems like a wrong practice to spawn yarn/npm from lifecycle scripts.
It might interfere with integrity checks, concurrency controls, caches and all the possible configurations Yarn has.

Why do you need to spawn package installation?

To answer the question Yarn exposes `npm_execpath` env variable to execution scripts which would point to Yarn.

**Comment by srl295** [comment] 2017-05-15 20:09
> Why do you need to spawn package installation?

Because I need to _calculate_ the actual package to be installed. It depends on the version of node, endianness of the actual system running, etc.

**Comment by bestander** [comment] 2017-05-15 20:12
I wonder if some smart optional dependencies mechanism should be in Yarn to
facilitate this

**Comment by srl295** [comment] 2017-05-15 20:17
`npm i full-icu` is trying to do the equivalent of:

```bash
$ node -p "'icu4c-data@'+process.versions.icu.split('.')[0] + os.endianness()[0].toLowerCase()"
icu4c-data@59l
$ npm i icu4c-data@59l
/tmp
└── icu4c-data@0.59.2 
```

**Comment by marvinhagemeister** [comment] 2017-05-16 08:18
I worked around this by treating the package `icu4c-data` as a normal binary. Luckily the naming scheme of the different endianness versions is consistent starting with version `0.56.0:

- `e` always stands for `x.x.0`
- `b` always stands for `x.x.1`
- `l` always stands for `x.x.2`

```bash
$ npm dist-tags ls icu4c-data
54b: 0.54.1
54l: 0.54.3
55b: 0.55.1
55l: 0.55.2
56b: 0.56.1
56e: 0.56.0
56l: 0.56.2
57b: 0.57.1
57e: 0.57.0
57l: 0.57.2
58b: 0.58.1
58e: 0.58.0
58l: 0.58.2
59b: 0.59.1
59e: 0.59.0
59l: 0.59.2
latest: 0.57.2
```

With this in mind [I wrote a simple package](https://github.com/marvinhagemeister/node-icu) that downloads the correct `.tgz` package file of `icu4c-date` directly from the npm registry and extracts only the `.dat` file into the current directory. Works perfectly fine with yarn (only tested on node 7+ and mac/linux).

This may not be the most elegant solution, but works great in our use case at work.

**Comment by srl295** [comment] 2017-05-16 15:52
So, one thing is, it's OK to have more ICU data files than needed. You could have all of them available in the directory, ICU will find the right one. 

@marvinhagemeister

first - very interesting, thanks for doing this. 

> `e` always stands for `x.x.0`
… yes, I did that on purpose.  Please don't rely on it, though.  As you probably know, you can't publish a package to the version more than once. So sometimes you get  `54l: 0.54.3` … Can't you just parse the dist tags?

And in any event— this is kind of the same as `full-icu` except it fetches using `http.get` yes?  Let's please combine forces because I plan to drastically change how `full-icu` works some year --> https://github.com/nodejs/node/issues/3460

**Comment by srl295** [comment] 2017-05-16 15:56
> ` Run "yarn add icu4c-data@58l" instead.`

so again… I think all `full-icu` needs is to know when it's running under yarn. 

@bestander I don't think the `npm_execpath` is the problem.  I'm finding yarn OK, the problem is how do I know that npm is really yarn so that I call `add` instead of `install`? I'll dig around

**Comment by bestander** [comment] 2017-05-16 16:03
I did not find any sort of UA string exposed to lifecycle scripts.
But again I think it is wrong to call yarn or npm from postinstall scripts,
that work should be done by curl/wget and not a full blown package manager.

**Comment by srl295** [comment] 2017-05-16 16:16
@bestander  there is a literal UA string… but anyway… i will try checking for `yarn.js` for now. 

> But again I think it is wrong to call yarn or npm from postinstall scripts,
> that work should be done by curl/wget and not a full blown package manager.

so I'm trying to make a dynamic dependency. The data file is 25Mb, and there are three versions updated yearly. The package manager allows that data to be cached alongside other resources. I don't have the data files stored anywhere else. Please do join in and comment on https://github.com/nodejs/node/issues/3460 especially, would really like input on how this should go.

**Comment by srl295** [comment] 2017-05-16 17:18
@shouze @bestander try `full-icu@1.1.3` now, should work in npm and yarn

**Comment by marvinhagemeister** [comment] 2017-05-16 17:49
@srl295 Thanks for the suggestion. We needed this quickly and I haven't found an easy way to check dist-tags yet. Perhaps one can query the tags from the registry directly? I'll check that.

Regarding installing packages in `lifecycle`-scripts: I'm with @bestander on this one. The whole point of yarn (and somewhat npm5 is going in the same direction) is to have reproducible builds. Any package installed via the package manger has to be listed inside the corresponding field in `package.json`, otherwise it wouldn't be reproducible. The only exception are native modules which are downloaded via a lifecycle script usually.

So a simple `yarn add icu4c-data@version` won't work as it will put the package into the `dependencies` field. See the recent commit to this repo: https://github.com/unicode-org/full-icu-npm/commit/0d4203ebf871b9b0b2c576b9b795a393905f46da . There's a chance that npm5 will share the same behaviour with their new lockfile (haven't checked yet).

**Comment by marvinhagemeister** [comment] 2017-05-16 18:27
@srl295 `yarn` always modifies the package.json :)

**Comment by shouze** [comment] 2017-06-06 10:13
hi guys I have bad news, I've tried with nodejs 8 & yarn 0.24.6 and...
```
error /home/node/node_modules/full-icu: Command failed.
Exit code: 1
Command: sh
Arguments: -c node postinstall.js
Directory: /home/node/node_modules/full-icu
Output:
npm install icu4c-data@59l (Node 8.0.0 and small-icu 59.1) -> icudt59l.dat
full-icu$ /usr/local/bin/node /home/node/.yarn/bin/yarn install icu4c-data@59l
yarn install v0.24.6
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add icu4c-data@59l" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/home/node/node_modules/full-icu/install-spawn.js:41
throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
^

Error: /usr/local/bin/node /home/node/.yarn/bin/yarn install icu4c-data@59l --> status 1
at npmInstallNpm (/home/node/node_modules/full-icu/install-spawn.js:41:9)
at Object.<anonymous> (/home/node/node_modules/full-icu/postinstall.js:68:2)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Function.Module.runMain (module.js:605:10)
at startup (bootstrap_node.js:158:16)
at bootstrap_node.js:575:3
```

Looks like:
- 1st, npm_execpath is not part of my process.env, but I can easily fix that by setting up the corresponding env var.
- The test in [install-spawn.js#L22](https://github.com/unicode-org/full-icu-npm/blob/acd2208ee5854f48c015d144dbd5605cd1ac0504/install-spawn.js#L22) is not the good one, yarn bin is named yarn and not yarn.js on my side so... even if I declare the right env var it fails.

@bestander @srl295 do you think it's ok if I make a patch in install-spawn.js to change the tested regex into something like that:

```js 
if ( /yarn(\.js)?$/.test(npmPath) ) {
```

**Comment by marvinhagemeister** [comment] 2017-06-06 19:36
@shouze That is quite curious. I've stumbled upon this error today as well, but cannot reproduce it. A second run does work fine for me. Not sure what is happening under the hood.

**Comment by srl295** [comment] 2017-06-06 19:51
@shouze please open a new PR but that sounds ok.  Why is `npm_execpath` not set?

@marvinhagemeister Perhaps a 2nd time the data is already installed?

**Comment by srl295** [comment] 2017-06-06 19:54
I'll reopen the issue…

**Comment by shouze** [comment] 2017-06-11 15:27
@srl295 ok I've pushed a patch over there https://github.com/unicode-org/full-icu-npm/pull/14

**Comment by shouze** [comment] 2017-06-15 19:16
@srl295 I've signed the CLA, and ci is green, ready to merge if you thing that the patch makes sense.

@bestander agree with that patch too?

**Comment by bestander** [comment] 2017-06-15 20:12
I guess it could work better but I am not a huge fan of the solution in general.

**Comment by shouze** [comment] 2017-06-15 20:13
Me neither...

**Comment by shouze** [comment] 2017-06-15 23:34
@srl295 thx! I've checked on my apps it's ok I confirm it's working well. So this issue could be closed... after a release on npm registry?

**Comment by srl295** [comment] 2017-07-31 16:34
Fixed in #14  and published as @1.2.0

**Closed by srl295** 2017-07-31 16:34 UTC

**Comment by OliverJAsh** [comment] 2018-02-17 19:09
I ran into this issue with full-icu version 1.2.0 and Yarn 1.3.2.

The specific issue I ran into seems to be related to Yarn workspaces. This fails:

```
yarn workspace server add full-icu
```

As a workaround, if I `cd` to the workspace and run:

```
yarn add full-icu
```

it works.

**Comment by srl295** [comment] 2018-02-17 19:33
@oliverjash not familiar with workspaces . Want to open a new issue?

**Comment by OliverJAsh** [comment] 2018-02-17 19:49
https://github.com/unicode-org/full-icu-npm/issues/22
